package com.mycompany.universityproject.frames;

import entity.Discipline;

import javax.swing.*;

/**
 *
 * @author proxc
 */
public class AdminPage extends UserPage {

    SpecialitiesPage        specialitiesPage        = new SpecialitiesPage();
    DisciplinesPage         disciplinesPage         = new DisciplinesPage();
    GroupsPage              groupsPage              = new GroupsPage();
    StudentsPage            studentsPage            = new StudentsPage();
    TeachersPage            teachersPage            = new TeachersPage();
    LaboratoryExercisesPage laboratoryExercisesPage = new LaboratoryExercisesPage();
    /**
     * Creates new form Home
     */
    public AdminPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pagePanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        descriptionLabel = new javax.swing.JLabel();
        exitIcon = new javax.swing.JLabel();
        pageNameLabel = new javax.swing.JLabel();
        logoIcon = new javax.swing.JLabel();
        laboratoryExercisesPanel = new javax.swing.JPanel();
        laboratoryExercisesLabel = new javax.swing.JLabel();
        laboratoryExercisesIcon = new javax.swing.JLabel();
        specialitiesPanel = new javax.swing.JPanel();
        specialitiesIcon = new javax.swing.JLabel();
        specialitiesLabel = new javax.swing.JLabel();
        disciplinesPanel = new javax.swing.JPanel();
        disciplinesLabel = new javax.swing.JLabel();
        disciplinesIcon = new javax.swing.JLabel();
        groupsPanel = new javax.swing.JPanel();
        groupsLabel = new javax.swing.JLabel();
        groupsIcon = new javax.swing.JLabel();
        studentsPanel = new javax.swing.JPanel();
        studentsLabel = new javax.swing.JLabel();
        studentsIcon = new javax.swing.JLabel();
        teachersPanel = new javax.swing.JPanel();
        teachersLabel = new javax.swing.JLabel();
        teachersIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        pagePanel.setBackground(new java.awt.Color(255, 255, 255));
        pagePanel.setMinimumSize(new java.awt.Dimension(860, 600));
        pagePanel.setPreferredSize(new java.awt.Dimension(854, 600));
        pagePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerPanel.setBackground(new java.awt.Color(45, 118, 232));
        headerPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerPanelMouseDragged(evt);
            }
        });
        headerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerPanelMousePressed(evt);
            }
        });
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        descriptionLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        descriptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        descriptionLabel.setText("University management system");
        headerPanel.add(descriptionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        exitIcon.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        exitIcon.setForeground(new java.awt.Color(255, 255, 255));
        exitIcon.setText("X");
        exitIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitIconMousePressed(evt);
            }
        });
        headerPanel.add(exitIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(838, 0, 22, -1));

        pageNameLabel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        pageNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        pageNameLabel.setText("Administrator");
        headerPanel.add(pageNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        logoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        headerPanel.add(logoIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 150, 130));

        pagePanel.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 240));

        laboratoryExercisesPanel.setBackground(java.awt.SystemColor.controlHighlight);
        laboratoryExercisesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laboratoryExercisesPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                laboratoryExercisesPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                laboratoryExercisesPanelMousePressed(evt);
            }
        });

        laboratoryExercisesLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        laboratoryExercisesLabel.setForeground(new java.awt.Color(45, 118, 232));
        laboratoryExercisesLabel.setText("Laboratory Exercises");

        laboratoryExercisesIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/laboratory_exercise.png"))); // NOI18N

        javax.swing.GroupLayout laboratoryExercisesPanelLayout = new javax.swing.GroupLayout(laboratoryExercisesPanel);
        laboratoryExercisesPanel.setLayout(laboratoryExercisesPanelLayout);
        laboratoryExercisesPanelLayout.setHorizontalGroup(
            laboratoryExercisesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laboratoryExercisesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(laboratoryExercisesLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, laboratoryExercisesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(laboratoryExercisesIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        laboratoryExercisesPanelLayout.setVerticalGroup(
            laboratoryExercisesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laboratoryExercisesPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(laboratoryExercisesIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laboratoryExercisesLabel)
                .addContainerGap())
        );

        pagePanel.add(laboratoryExercisesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, 140, 120));

        specialitiesPanel.setBackground(java.awt.SystemColor.controlHighlight);
        specialitiesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                specialitiesPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                specialitiesPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                specialitiesPanelMousePressed(evt);
            }
        });

        specialitiesIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/specialities.png"))); // NOI18N

        specialitiesLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        specialitiesLabel.setForeground(new java.awt.Color(45, 118, 232));
        specialitiesLabel.setText("Specialities");

        javax.swing.GroupLayout specialitiesPanelLayout = new javax.swing.GroupLayout(specialitiesPanel);
        specialitiesPanel.setLayout(specialitiesPanelLayout);
        specialitiesPanelLayout.setHorizontalGroup(
            specialitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, specialitiesPanelLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(specialitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(specialitiesPanelLayout.createSequentialGroup()
                        .addComponent(specialitiesIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, specialitiesPanelLayout.createSequentialGroup()
                        .addComponent(specialitiesLabel)
                        .addGap(35, 35, 35))))
        );
        specialitiesPanelLayout.setVerticalGroup(
            specialitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(specialitiesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(specialitiesIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(specialitiesLabel)
                .addContainerGap())
        );

        pagePanel.add(specialitiesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 140, 120));

        disciplinesPanel.setBackground(java.awt.SystemColor.controlHighlight);
        disciplinesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                disciplinesPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                disciplinesPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                disciplinesPanelMousePressed(evt);
            }
        });

        disciplinesLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        disciplinesLabel.setForeground(new java.awt.Color(45, 118, 232));
        disciplinesLabel.setText("Disciplines");

        disciplinesIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/disciplines.png"))); // NOI18N

        javax.swing.GroupLayout disciplinesPanelLayout = new javax.swing.GroupLayout(disciplinesPanel);
        disciplinesPanel.setLayout(disciplinesPanelLayout);
        disciplinesPanelLayout.setHorizontalGroup(
            disciplinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(disciplinesPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(disciplinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(disciplinesIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(disciplinesPanelLayout.createSequentialGroup()
                        .addComponent(disciplinesLabel)
                        .addGap(0, 29, Short.MAX_VALUE)))
                .addContainerGap())
        );
        disciplinesPanelLayout.setVerticalGroup(
            disciplinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(disciplinesPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(disciplinesIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(disciplinesLabel)
                .addContainerGap())
        );

        pagePanel.add(disciplinesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 140, 120));

        groupsPanel.setBackground(java.awt.SystemColor.controlHighlight);
        groupsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                groupsPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                groupsPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                groupsPanelMousePressed(evt);
            }
        });

        groupsLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        groupsLabel.setForeground(new java.awt.Color(45, 118, 232));
        groupsLabel.setText("Groups");

        groupsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/groups.png"))); // NOI18N

        javax.swing.GroupLayout groupsPanelLayout = new javax.swing.GroupLayout(groupsPanel);
        groupsPanel.setLayout(groupsPanelLayout);
        groupsPanelLayout.setHorizontalGroup(
            groupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupsPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(groupsLabel)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, groupsPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(groupsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        groupsPanelLayout.setVerticalGroup(
            groupsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupsPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(groupsIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(groupsLabel)
                .addContainerGap())
        );

        pagePanel.add(groupsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 140, 120));

        studentsPanel.setBackground(java.awt.SystemColor.controlHighlight);
        studentsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                studentsPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                studentsPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                studentsPanelMousePressed(evt);
            }
        });

        studentsLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        studentsLabel.setForeground(new java.awt.Color(45, 118, 232));
        studentsLabel.setText("Students");

        studentsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/students.png"))); // NOI18N

        javax.swing.GroupLayout studentsPanelLayout = new javax.swing.GroupLayout(studentsPanel);
        studentsPanel.setLayout(studentsPanelLayout);
        studentsPanelLayout.setHorizontalGroup(
            studentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentsPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(studentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentsIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(studentsPanelLayout.createSequentialGroup()
                        .addComponent(studentsLabel)
                        .addGap(0, 27, Short.MAX_VALUE)))
                .addContainerGap())
        );
        studentsPanelLayout.setVerticalGroup(
            studentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentsIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentsLabel)
                .addContainerGap())
        );

        pagePanel.add(studentsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 140, 120));

        teachersPanel.setBackground(java.awt.SystemColor.controlHighlight);
        teachersPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                teachersPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                teachersPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                teachersPanelMousePressed(evt);
            }
        });

        teachersLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        teachersLabel.setForeground(new java.awt.Color(45, 118, 232));
        teachersLabel.setText("Teachers");

        teachersIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/teachers.png"))); // NOI18N

        javax.swing.GroupLayout teachersPanelLayout = new javax.swing.GroupLayout(teachersPanel);
        teachersPanel.setLayout(teachersPanelLayout);
        teachersPanelLayout.setHorizontalGroup(
            teachersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teachersPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(teachersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teachersIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(teachersPanelLayout.createSequentialGroup()
                        .addComponent(teachersLabel)
                        .addGap(0, 33, Short.MAX_VALUE)))
                .addContainerGap())
        );
        teachersPanelLayout.setVerticalGroup(
            teachersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, teachersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(teachersIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teachersLabel)
                .addContainerGap())
        );

        pagePanel.add(teachersPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 140, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 589, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitIconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitIconMousePressed
        // TODO add your handling code here:
        dispose();
        specialitiesPage       .dispose();
        disciplinesPage        .dispose();
        groupsPage             .dispose();
        studentsPage           .dispose();
        teachersPage           .dispose();
        laboratoryExercisesPage.dispose();

    }//GEN-LAST:event_exitIconMousePressed

    private void specialitiesPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_specialitiesPanelMouseEntered
        // TODO add your handling code here:
        setColor(specialitiesPanel);
    }//GEN-LAST:event_specialitiesPanelMouseEntered

    private void specialitiesPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_specialitiesPanelMouseExited
        // TODO add your handling code here:
        resetColor(specialitiesPanel);
    }//GEN-LAST:event_specialitiesPanelMouseExited
     
    
    
    
    int xx,xy;
    private void headerPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerPanelMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_headerPanelMousePressed

    private void headerPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerPanelMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);  
    }//GEN-LAST:event_headerPanelMouseDragged

    private void disciplinesPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disciplinesPanelMouseEntered
        // TODO add your handling code here:
        setColor(disciplinesPanel);
    }//GEN-LAST:event_disciplinesPanelMouseEntered

    private void disciplinesPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disciplinesPanelMouseExited
        // TODO add your handling code here:
        resetColor(disciplinesPanel);
    }//GEN-LAST:event_disciplinesPanelMouseExited

    private void groupsPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_groupsPanelMouseEntered
        // TODO add your handling code here
        setColor(groupsPanel);
    }//GEN-LAST:event_groupsPanelMouseEntered

    private void groupsPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_groupsPanelMouseExited
        // TODO add your handling code here:
        resetColor(groupsPanel);
    }//GEN-LAST:event_groupsPanelMouseExited

    private void studentsPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentsPanelMouseEntered
        // TODO add your handling code here:
        setColor(studentsPanel);
    }//GEN-LAST:event_studentsPanelMouseEntered

    private void studentsPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentsPanelMouseExited
        // TODO add your handling code here:
        resetColor(studentsPanel);
        
    }//GEN-LAST:event_studentsPanelMouseExited

    private void teachersPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teachersPanelMouseEntered
        // TODO add your handling code here:
        setColor(teachersPanel);
    }//GEN-LAST:event_teachersPanelMouseEntered

    private void teachersPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teachersPanelMouseExited
        // TODO add your handling code here:
        resetColor(teachersPanel);
    }//GEN-LAST:event_teachersPanelMouseExited

    private void laboratoryExercisesPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laboratoryExercisesPanelMouseEntered
        // TODO add your handling code here:
        setColor(laboratoryExercisesPanel);
    }//GEN-LAST:event_laboratoryExercisesPanelMouseEntered

    private void laboratoryExercisesPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laboratoryExercisesPanelMouseExited
        // TODO add your handling code here:
        resetColor(laboratoryExercisesPanel);
    }//GEN-LAST:event_laboratoryExercisesPanelMouseExited

    private void specialitiesPanelMousePressed(java.awt.event.MouseEvent evt) {                                               

        specialitiesPage.setVisible(true);
    }

    private void disciplinesPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disciplinesPanelMousePressed
        // TODO add your handling code here:
        //just a sample.

        disciplinesPage.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        disciplinesPage.setVisible(true);
    }//GEN-LAST:event_disciplinesPanelMousePressed

    private void studentsPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentsPanelMousePressed
        // TODO add your handling code here:
        studentsPage.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        studentsPage.setVisible(true);
    }//GEN-LAST:event_studentsPanelMousePressed

    private void groupsPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_groupsPanelMousePressed
        groupsPage.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_groupsPanelMousePressed

    private void teachersPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teachersPanelMousePressed
        teachersPage.setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_teachersPanelMousePressed

    private void laboratoryExercisesPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laboratoryExercisesPanelMousePressed
        laboratoryExercisesPage.setVisible(true);// ;
    }//GEN-LAST:event_laboratoryExercisesPanelMousePressed
 public void setColor(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(197, 197, 197));
 }
 
 public void resetColor(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(240,240,240));
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel disciplinesIcon;
    private javax.swing.JLabel disciplinesLabel;
    private javax.swing.JPanel disciplinesPanel;
    private javax.swing.JLabel exitIcon;
    private javax.swing.JLabel groupsIcon;
    private javax.swing.JLabel groupsLabel;
    private javax.swing.JPanel groupsPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel laboratoryExercisesIcon;
    private javax.swing.JLabel laboratoryExercisesLabel;
    private javax.swing.JPanel laboratoryExercisesPanel;
    private javax.swing.JLabel logoIcon;
    private javax.swing.JLabel pageNameLabel;
    private javax.swing.JPanel pagePanel;
    private javax.swing.JLabel specialitiesIcon;
    private javax.swing.JLabel specialitiesLabel;
    private javax.swing.JPanel specialitiesPanel;
    private javax.swing.JLabel studentsIcon;
    private javax.swing.JLabel studentsLabel;
    private javax.swing.JPanel studentsPanel;
    private javax.swing.JLabel teachersIcon;
    private javax.swing.JLabel teachersLabel;
    private javax.swing.JPanel teachersPanel;
    // End of variables declaration//GEN-END:variables
}
