/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.universityproject.frames;

/**
 *
 * @author proxc
 */
public class StudentPage extends UserPage {

    StudentDisciplinesPage studentDisciplinesPage = new StudentDisciplinesPage();
    StudentLaboratoryExercisesPage studentLaboratoryExercisesPage = new StudentLaboratoryExercisesPage();
    /**
     * Creates new form Home_Data
     */
    public StudentPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        panelLabel = new javax.swing.JLabel();
        exitIcon = new javax.swing.JLabel();
        pagePanel = new javax.swing.JPanel();
        disciplinesPanel = new javax.swing.JPanel();
        disciplinesLabel = new javax.swing.JLabel();
        disciplinesIcon = new javax.swing.JLabel();
        laboratoryExercisesPanel = new javax.swing.JPanel();
        laboratoryExercisesLabel = new javax.swing.JLabel();
        laboratoryExercisesIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        topPanel.setBackground(new java.awt.Color(45, 118, 232));

        panelLabel.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        panelLabel.setForeground(new java.awt.Color(255, 255, 255));
        panelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelLabel.setText("Student");

        exitIcon.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        exitIcon.setForeground(new java.awt.Color(255, 255, 255));
        exitIcon.setText("X");
        exitIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitIconMousePressed(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(panelLabel)
                .addContainerGap(468, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addComponent(exitIcon)
                .addGap(10, 10, 10)
                .addComponent(panelLabel)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pagePanel.setBackground(new java.awt.Color(255, 255, 255));

        disciplinesPanel.setBackground(java.awt.SystemColor.controlHighlight);
        disciplinesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                disciplinesPanelMousePressed(evt);
            }
        });

        disciplinesLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        disciplinesLabel.setForeground(new java.awt.Color(45, 118, 232));
        disciplinesLabel.setText("My disciplines");

        disciplinesIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/disciplines.png"))); // NOI18N

        javax.swing.GroupLayout disciplinesPanelLayout = new javax.swing.GroupLayout(disciplinesPanel);
        disciplinesPanel.setLayout(disciplinesPanelLayout);
        disciplinesPanelLayout.setHorizontalGroup(
            disciplinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(disciplinesPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(disciplinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(disciplinesLabel)
                    .addComponent(disciplinesIcon))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        disciplinesPanelLayout.setVerticalGroup(
            disciplinesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(disciplinesPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(disciplinesIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(disciplinesLabel)
                .addContainerGap())
        );

        laboratoryExercisesPanel.setBackground(java.awt.SystemColor.controlHighlight);
        laboratoryExercisesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                laboratoryExercisesPanelMousePressed(evt);
            }
        });

        laboratoryExercisesLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        laboratoryExercisesLabel.setForeground(new java.awt.Color(45, 118, 232));
        laboratoryExercisesLabel.setText("Laboratory Exercises");

        laboratoryExercisesIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/laboratory_exercise.png"))); // NOI18N

        javax.swing.GroupLayout laboratoryExercisesPanelLayout = new javax.swing.GroupLayout(laboratoryExercisesPanel);
        laboratoryExercisesPanel.setLayout(laboratoryExercisesPanelLayout);
        laboratoryExercisesPanelLayout.setHorizontalGroup(
            laboratoryExercisesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laboratoryExercisesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(laboratoryExercisesLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, laboratoryExercisesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(laboratoryExercisesIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        laboratoryExercisesPanelLayout.setVerticalGroup(
            laboratoryExercisesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laboratoryExercisesPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(laboratoryExercisesIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laboratoryExercisesLabel)
                .addContainerGap())
        );

        javax.swing.GroupLayout pagePanelLayout = new javax.swing.GroupLayout(pagePanel);
        pagePanel.setLayout(pagePanelLayout);
        pagePanelLayout.setHorizontalGroup(
            pagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pagePanelLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(disciplinesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(laboratoryExercisesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );
        pagePanelLayout.setVerticalGroup(
            pagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pagePanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(pagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(disciplinesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laboratoryExercisesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 238, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 119, Short.MAX_VALUE)
                    .addComponent(pagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void disciplinesPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disciplinesPanelMousePressed
        // TODO add your handling code here:
        //just a sample.

        studentDisciplinesPage.setData(getUser().getIdentifier());
        studentDisciplinesPage.setVisible(true);

    }//GEN-LAST:event_disciplinesPanelMousePressed

    private void laboratoryExercisesPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laboratoryExercisesPanelMousePressed

        studentLaboratoryExercisesPage.setData(getUser().getIdentifier());
        studentLaboratoryExercisesPage.setVisible(true);
    }//GEN-LAST:event_laboratoryExercisesPanelMousePressed

    private void exitIconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitIconMousePressed
        // TODO add your handling code here:
        dispose();
        studentDisciplinesPage.dispose();
        studentLaboratoryExercisesPage.dispose();

    }//GEN-LAST:event_exitIconMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel disciplinesIcon;
    private javax.swing.JLabel disciplinesLabel;
    private javax.swing.JPanel disciplinesPanel;
    private javax.swing.JLabel exitIcon;
    private javax.swing.JLabel laboratoryExercisesIcon;
    private javax.swing.JLabel laboratoryExercisesLabel;
    private javax.swing.JPanel laboratoryExercisesPanel;
    private javax.swing.JPanel pagePanel;
    private javax.swing.JLabel panelLabel;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
