/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.universityproject.frames;

import entity.*;
import enums.Degree;
import enums.GroupNumber;
import enums.RoleEnum;
import enums.UniversityUID;
import services.*;
import validators.FieldValidator;

import java.awt.Color;
import java.util.Arrays;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author proxc
 */
public class TeachersPage extends javax.swing.JFrame {

    Teacher currentTeacher;
    /**
     * Creates new form Home15
     */
    public TeachersPage() {
        currentTeacher = null;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        pageNameLabel = new javax.swing.JLabel();
        exitIcon = new javax.swing.JLabel();
        editButton = new javax.swing.JLabel();
        listButton = new javax.swing.JLabel();
        home = new javax.swing.JPanel();
        listPanel = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        entityTable = new javax.swing.JTable();
        editPanel = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        studentNameLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        identifierField = new javax.swing.JTextField();
        studentNameLabel4 = new javax.swing.JLabel();
        studentNameLabel5 = new javax.swing.JLabel();
        phoneNumberField = new javax.swing.JTextField();
        studentNameLabel1 = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        studentNameLabel2 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        studentNameLabel6 = new javax.swing.JLabel();
        degreeCombo = new javax.swing.JComboBox<>();
        errorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        main.setBackground(new java.awt.Color(255, 255, 255));

        header.setBackground(new java.awt.Color(45, 118, 232));
        header.setPreferredSize(new java.awt.Dimension(838, 200));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        pageNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        pageNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        pageNameLabel.setText("Teachers");

        exitIcon.setBackground(new java.awt.Color(45, 118, 232));
        exitIcon.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        exitIcon.setForeground(new java.awt.Color(255, 255, 255));
        exitIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitIcon.setText("X");
        exitIcon.setOpaque(true);
        exitIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitIconMouseClicked(evt);
            }
        });

        editButton.setBackground(new java.awt.Color(45, 118, 232));
        editButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editButton.setForeground(new java.awt.Color(255, 255, 255));
        editButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editButton.setText("Add/Edit teacher");
        editButton.setOpaque(true);
        editButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editButtonMouseClicked(evt);
            }
        });

        listButton.setBackground(new java.awt.Color(45, 118, 232));
        listButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        listButton.setForeground(new java.awt.Color(255, 255, 255));
        listButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listButton.setText("Teachers");
        listButton.setOpaque(true);
        listButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(pageNameLabel))
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(listButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addComponent(exitIcon)
                .addGap(30, 30, 30)
                .addComponent(pageNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        home.setLayout(new java.awt.CardLayout());

        listPanel.setBackground(new java.awt.Color(255, 255, 255));
        listPanel.setLayout(new javax.swing.BoxLayout(listPanel, javax.swing.BoxLayout.LINE_AXIS));

        scrollPane.setBackground(new java.awt.Color(255, 255, 255));
        scrollPane.setBorder(null);

        entityTable.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        entityTable.setForeground(new java.awt.Color(51, 51, 51));
        entityTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        entityTable.setGridColor(new java.awt.Color(255, 255, 255));
        entityTable.setRowHeight(20);
        entityTable.setSelectionBackground(new java.awt.Color(1, 198, 83));
        scrollPane.setViewportView(entityTable);

        listPanel.add(scrollPane);

        home.add(listPanel, "card3");

        editPanel.setBackground(new java.awt.Color(255, 255, 255));

        saveButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        saveButton.setForeground(new java.awt.Color(45, 118, 232));
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        studentNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        studentNameLabel.setForeground(new java.awt.Color(45, 118, 232));
        studentNameLabel.setText("First name");

        firstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFieldActionPerformed(evt);
            }
        });

        identifierField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identifierFieldActionPerformed(evt);
            }
        });

        studentNameLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        studentNameLabel4.setForeground(new java.awt.Color(45, 118, 232));
        studentNameLabel4.setText("Identifier");

        studentNameLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        studentNameLabel5.setForeground(new java.awt.Color(45, 118, 232));
        studentNameLabel5.setText("Phone number");

        phoneNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberFieldActionPerformed(evt);
            }
        });

        studentNameLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        studentNameLabel1.setForeground(new java.awt.Color(45, 118, 232));
        studentNameLabel1.setText("Last name");

        lastNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameFieldActionPerformed(evt);
            }
        });

        studentNameLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        studentNameLabel2.setForeground(new java.awt.Color(45, 118, 232));
        studentNameLabel2.setText("Email");

        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });

        studentNameLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        studentNameLabel6.setForeground(new java.awt.Color(45, 118, 232));
        studentNameLabel6.setText("Degree");

        errorLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout editPanelLayout = new javax.swing.GroupLayout(editPanel);
        editPanel.setLayout(editPanelLayout);
        editPanelLayout.setHorizontalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(degreeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPanelLayout.createSequentialGroup()
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentNameLabel2))
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(phoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(editPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(studentNameLabel6))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPanelLayout.createSequentialGroup()
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentNameLabel1)
                            .addComponent(studentNameLabel))
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(studentNameLabel4)
                                    .addComponent(identifierField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(editPanelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(studentNameLabel5)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 268, Short.MAX_VALUE))
                    .addComponent(errorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        editPanelLayout.setVerticalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studentNameLabel)
                            .addComponent(studentNameLabel4))
                        .addGap(1, 1, 1)
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(identifierField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studentNameLabel1)
                            .addComponent(studentNameLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studentNameLabel6)
                            .addComponent(studentNameLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emailField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(degreeCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)))
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveButton)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        home.add(editPanel, "card3");

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initEntityTable() {
        String[] columnNames = {"Teacher", "Identifier", "Email", "Phone number"};

        TeacherService teacherService = new TeacherService();
        List<Teacher> teachers = teacherService.getAll();

        Object[][] data = new Object[teachers.size()][columnNames.length];

        int index = 0;
        for(Teacher teacher : teachers) {
            data[index][0] = teacher.getName();
            data[index][1] = teacher.getUser().getIdentifier();
            data[index][2] = teacher.getUser().getEmail();
            data[index][3] = teacher.getUser().getPhoneNumber();
            index++;
        }

        DefaultTableModel model = new DefaultTableModel(data, columnNames);

        entityTable.setModel(model);
        entityTable.setGridColor(new Color(255, 255, 255));
        entityTable.setRowHeight(20);
        entityTable.setSelectionBackground(new Color(45, 118, 232));
        scrollPane.setViewportView(entityTable);

        listPanel.add(scrollPane);
    }

    int xx;
    int xy;
    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
       
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_headerMouseDragged

    private void exitIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitIconMouseClicked
        // TODO add your handling code here:
        hide();
    }//GEN-LAST:event_exitIconMouseClicked

    private void listButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listButtonMouseClicked
        // TODO add your handling code here:
        
        setLblColor(listButton);
        resetLblColor(editButton);
        //switch bettween Jpanels
        editPanel.setVisible(false);
        listPanel.setVisible(true);
        initEntityTable();
      
    }//GEN-LAST:event_listButtonMouseClicked

    private void editButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseClicked

        currentTeacher = null;
        emptyControls();

        int column = 1;
        int row = entityTable.getSelectedRow();

        List<Degree> degrees = Arrays.asList(Degree.values());
        DefaultComboBoxModel defaultComboBoxModel = new DefaultComboBoxModel();
        defaultComboBoxModel.addAll(degrees);
        degreeCombo.setModel(defaultComboBoxModel);

        if (row < 0){
            setLblColor(editButton);
            resetLblColor(listButton);
            editPanel.setVisible(true);
            listPanel.setVisible(false);
            return;
        }

        String identifier = entityTable.getModel().getValueAt(row, column).toString();
        TeacherService teacherService = new TeacherService();
        currentTeacher = teacherService.getTeacher(identifier);
        if( currentTeacher == null )
            return;

        fillFields();
        setLblColor(editButton);
        resetLblColor(listButton);
        editPanel.setVisible(true);
        listPanel.setVisible(false);
        return;

    }//GEN-LAST:event_editButtonMouseClicked

    private void fillFields() {

        firstNameField.setText(currentTeacher.getUser().getFirstName());
        lastNameField.setText(currentTeacher.getUser().getLastName());
        identifierField.setText(currentTeacher.getUser().getIdentifier());
        phoneNumberField.setText(currentTeacher.getUser().getPhoneNumber());
        emailField.setText(currentTeacher.getUser().getEmail());
        degreeCombo.setSelectedItem(currentTeacher.getDegree());
    }

    private void emptyControls() {

        firstNameField.setText("");
        lastNameField.setText("");
        identifierField.setText("");
        phoneNumberField.setText("");
        emailField.setText("");
        degreeCombo.setSelectedItem(0);
    }

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed

        if( !validateData() )
            return;
        
        if( currentTeacher == null ){
            addNewRecord();
            return;
        }

        currentTeacher.getUser().setFirstName(firstNameField.getText());
        currentTeacher.getUser().setLastName(lastNameField.getText());
        currentTeacher.getUser().setIdentifier(identifierField.getText());
        currentTeacher.getUser().setPhoneNumber(phoneNumberField.getText());
        currentTeacher.getUser().setEmail(emailField.getText());
        currentTeacher.setDegree((Degree)degreeCombo.getSelectedItem());

        TeacherService teacherService = new TeacherService();
        teacherService.saveOrUpdate(currentTeacher);

        setLblColor(listButton);
        resetLblColor(editButton);

        editPanel.setVisible(false);
        listPanel.setVisible(true);
        initEntityTable();
    }//GEN-LAST:event_saveButtonActionPerformed

    private boolean validateData() {

        errorLabel.setText("");

        if( !FieldValidator.validatePersonName(firstNameField, errorLabel ))
        {
            errorLabel.setText("Wrong input in first name");
            return false;
        }

        if( !FieldValidator.validatePersonName(lastNameField, errorLabel ))
        {
            errorLabel.setText("Wrong input in last name");
            return false;
        }

        if( !FieldValidator.validateEmail( emailField, errorLabel ))
            return false;

        if( !FieldValidator.validateNumericField( identifierField, errorLabel ))
        {
            errorLabel.setText("Wrong input in identifier");
            return false;
        }

        if( degreeCombo.getSelectedIndex() < 0 )
        {
            errorLabel.setText("Pick degree");
            return false;
        }

        return true;
    }

    private void firstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldActionPerformed

    private void identifierFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identifierFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identifierFieldActionPerformed

    private void phoneNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberFieldActionPerformed

    private void lastNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameFieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void addNewRecord() {

        currentTeacher = new Teacher();
        User user = new User();

        RoleService roleService = new RoleService();

        user.setRole(roleService.getRole(RoleEnum.Student));
        user.setFirstName(firstNameField.getText());
        user.setLastName(lastNameField.getText());
        user.setEmail(emailField.getText());
        user.setIdentifier(identifierField.getText());
        user.setPhoneNumber(phoneNumberField.getText());
        user.setPassword(identifierField.getText());
        user.setUsername(emailField.getText());

        currentTeacher.setDegree((Degree)degreeCombo.getSelectedItem());

        UserService userService = new UserService();

        currentTeacher.setUser(userService.saveOrUpdate(user));

        TeacherService teacherService = new TeacherService();
        teacherService.saveOrUpdate(currentTeacher);

        setLblColor(listButton);
        resetLblColor(editButton);

        editPanel.setVisible(false);
        listPanel.setVisible(true);
        initEntityTable();
    }
 
    // ------------switch between colors for Active/Inactive color
    public void setLblColor(JLabel lbl)
    {
        lbl.setBackground(new Color(45,118,255));
    }
    
      public void resetLblColor(JLabel lbl)
    {
        lbl.setBackground(new Color(45,118,232));
    }
      
           
      
      //-----------End --------
      
     //Let's create staff options and Avoid data
      
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //Change UI look of table.
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeachersPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeachersPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeachersPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeachersPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeachersPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> degreeCombo;
    private javax.swing.JLabel editButton;
    private javax.swing.JPanel editPanel;
    private javax.swing.JTextField emailField;
    private javax.swing.JTable entityTable;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel exitIcon;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JPanel header;
    private javax.swing.JPanel home;
    private javax.swing.JTextField identifierField;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel listButton;
    private javax.swing.JPanel listPanel;
    private javax.swing.JPanel main;
    private javax.swing.JLabel pageNameLabel;
    private javax.swing.JTextField phoneNumberField;
    private javax.swing.JButton saveButton;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JLabel studentNameLabel;
    private javax.swing.JLabel studentNameLabel1;
    private javax.swing.JLabel studentNameLabel2;
    private javax.swing.JLabel studentNameLabel4;
    private javax.swing.JLabel studentNameLabel5;
    private javax.swing.JLabel studentNameLabel6;
    // End of variables declaration//GEN-END:variables
}
